# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.database_dsn: '%kernel.project_dir%/var/rates.json'
    app.base_currency: '%env(BASE_CURRENCY)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $databaseDSN: '%app.database_dsn%'
            $baseCurrency: '%app.base_currency%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Tags
    _instanceof:
        App\Service\Api\ExchangeInterface:
            tags: [ 'app.api_exchange_service' ]

    App\Handler\UpdateCurrencyExchangeRateHandler:
        arguments:
            - !tagged { tag: 'app.api_exchange_service'}

    App\Service\Api\FloatratesExchangeService:
        arguments:
            $url: '%env(FLOATRATES_EXCHANGE_URL)%'
            $responseTransformer: '@App\Service\Transformer\FloatratesExchangeResponseTransformer'

    App\Service\Api\CoinpaprikaExchangeService:
        arguments:
            $url: '%env(COINPAPRIKA_EXCHANGE_URL)%'
            $responseTransformer: '@App\Service\Transformer\CoinpaprikaExchangeResponseTransformer'